export const dummyProducts = [
  {
    id: "1",
    name: "Beef Steak",
    category: "beef",
    pricePerKg: 750,
    image: "/products/beef.jpg",
    instock: false,
  },
  {
    id: "2",
    name: "Beef Mince",
    category: "beef",
    pricePerKg: 650,
    image: "/products/goat.jpg",
  },
  {
    id: "3",
    name: "Beef Ribs",
    category: "beef",
    pricePerKg: 700,
    image: "/products/beef.jpg",
  },
  {
    id: "4",
    name: "Goat Meat (Choma Cut)",
    category: "goat",
    pricePerKg: 900,
    image: "/products/goat.jpg",
  },
  {
    id: "5",
    name: "Goat Meat (Stew Cut)",
    category: "goat",
    pricePerKg: 850,
    image: "/products/beef.jpg",
  },
  {
    id: "6",
    name: "Lamb Chops",
    category: "lamb",
    pricePerKg: 1_100,
    image: "/products/goat.jpg",
  },
  {
    id: "7",
    name: "Lamb Shoulder",
    category: "lamb",
    pricePerKg: 1_000,
    image: "/products/beef.jpg",
  },
  {
    id: "8",
    name: "Mixed Meat Pack",
    category: "mixed",
    pricePerKg: 800,
    image: "/products/goat.jpg",
  },
];
